// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ports-domain-service.proto

package api

const (
	PortsDomainService_UpsertPort       = "/ports_domain_service.PortsDomainService/UpsertPort"
	PortsDomainService_BatchUpsertPorts = "/ports_domain_service.PortsDomainService/BatchUpsertPorts"
)

var (
	FullMethods = []string{
		PortsDomainService_UpsertPort,
		PortsDomainService_BatchUpsertPorts,
	}
)
